<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="../blog/home">Blog Vinc</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
            <!--ajouter la condition soit bouton connect soit bouton diconnect-->
            <?php if(!$_SESSION): ?>
               <a class="nav-link waves-effect waves-light" href="login">CONNECTION <span class="sr-only">(current)</span></a>
            <?php else: ?>
                <a class="nav-link waves-effect waves-light" href="disconnect">Deconnection <span class="sr-only">(current)</span></a>
            <?php endif; ?>
            </li>
            <li class="nav-item">
                <a class="nav-link waves-effect waves-light" href="register">Créer un compte</a>
            </li>
            <?php if($_SESSION): ?>
            <li class="nav-item active">
                <a class="nav-link waves-effect waves-light" href="#">Bonjour, <?= $_SESSION['prenom'] .' '. $_SESSION['nom'] ?></a>
            </li>
            <?php endif; ?>
        </ul>
        <form class="form-inline">
            <div class="md-form my-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
        </form>
    </div>
</nav>